"""all models complete

Revision ID: 7bef756682d8
Revises: ed0abe5c8348
Create Date: 2023-10-12 17:23:14.032982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bef756682d8'
down_revision = 'ed0abe5c8348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=False),
    sa.Column('totalPrice', sa.Float(), nullable=True),
    sa.Column('shippingAddress', sa.String(), nullable=False),
    sa.Column('billingAddress', sa.String(), nullable=False),
    sa.Column('paymentMethod', sa.String(), nullable=False),
    sa.Column('orderStatus', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['products.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('orders')
    # ### end Alembic commands ###